/**
 * RFC 7807 Problem Details for HTTP APIs
 * @see https://www.rfc-editor.org/rfc/rfc7807
 *
 * Provides a standard, machine-readable format for all API error responses.
 * Every 4xx / 5xx response body MUST conform to this shape.
 */

/**
 * The canonical JSON body for an RFC 7807 error response.
 *
 * - `type`     – A URI that identifies the problem type. Dereferencing the URI
 *                SHOULD yield human-readable documentation. Defaults to
 *                "about:blank" when no specific type is defined.
 * - `title`    – A short, human-readable summary of the problem type. It SHOULD
 *                NOT change between occurrences of the same problem (i.e. use
 *                the class name, not the per-instance message).
 * - `status`   – The HTTP status code generated by the origin server.
 * - `detail`   – A human-readable explanation specific to this occurrence.
 * - `instance` – A URI reference that identifies the specific occurrence.
 *                Typically the request path + a unique trace ID suffix.
 * - `errors`   – Optional map of field-level validation errors; non-standard
 *                extension field (RFC 7807 §3.2 allows extension members).
 */
export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance: string;
  errors?: Record<string, unknown> | null;
}

/**
 * Maps HTTP status codes to a stable `type` URI and a canonical `title`.
 * These URIs are intentionally relative so the app can host its own docs page.
 */
export const PROBLEM_TYPE_MAP: Record<
  number,
  { type: string; title: string }
> = {
  400: {
    type: "/problems/bad-request",
    title: "Bad Request",
  },
  401: {
    type: "/problems/unauthorized",
    title: "Unauthorized",
  },
  403: {
    type: "/problems/forbidden",
    title: "Forbidden",
  },
  404: {
    type: "/problems/not-found",
    title: "Not Found",
  },
  409: {
    type: "/problems/conflict",
    title: "Conflict",
  },
  422: {
    type: "/problems/unprocessable-entity",
    title: "Unprocessable Entity",
  },
  429: {
    type: "/problems/too-many-requests",
    title: "Too Many Requests",
  },
  500: {
    type: "/problems/internal-server-error",
    title: "Internal Server Error",
  },
  503: {
    type: "/problems/service-unavailable",
    title: "Service Unavailable",
  },
};

/**
 * Builds a fully-populated {@link ProblemDetails} object.
 *
 * @param status   HTTP status code (4xx / 5xx).
 * @param detail   Per-occurrence human-readable explanation.
 * @param instance The request path or a URI identifying the occurrence.
 * @param errors   Optional map of field-level errors (validation use case).
 * @param overrides Optional partial overrides for `type` and `title`.
 */
export function buildProblemDetails(
  status: number,
  detail: string,
  instance: string,
  errors?: Record<string, unknown> | null,
  overrides?: Partial<Pick<ProblemDetails, "type" | "title">>,
): ProblemDetails {
  const defaults = PROBLEM_TYPE_MAP[status] ?? {
    type: "about:blank",
    title: "Unknown Error",
  };

  return {
    type: overrides?.type ?? defaults.type,
    title: overrides?.title ?? defaults.title,
    status,
    detail,
    instance,
    ...(errors !== undefined && errors !== null ? { errors } : {}),
  };
}
